name: Validate Schema Change
on:
  issues:
    types: [opened, edited]

jobs:
  validate-schema:
    if: contains(github.event.issue.labels.*.name, 'schema-anpassen')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build Project with Maven
        run: mvn -f TopicConfig/pom.xml clean package

      - name: Download Schema Attachment
        working-directory: TopicConfig
        run: |
          echo "Extracting attachment URL from issue body..."
          attachment_url=$(echo "${{ github.event.issue.body }}" | grep -oE 'https://[^ ]+\.txt')
          echo "Found attachment URL: $attachment_url"
          if [ -z "$attachment_url" ]; then
            echo "No attachment URL found, exiting." && exit 1
          fi
          echo "Downloading file..."
          curl -L "$attachment_url" -o uploaded_schema.txt
          ls -l uploaded_schema.txt

      - name: Run SchemaReader and capture output
        working-directory: TopicConfig
        run: |
          mvn exec:java -Dexec.mainClass="de.nordlb.kafka.specification.schema.validation.SchemaReader" | tee schema_output.log

      - name: Debug List Files in TopicConfig
        working-directory: TopicConfig
        run: ls -l

      - name: Verify Schema Output
        working-directory: TopicConfig
        run: |
          if grep -q 'Ausgelesenes Schema:' schema_output.log; then
            echo "Schema wurde erfolgreich ausgelesen."
          else
            echo "Fehler: Schema-Ausgabe nicht gefunden!" && exit 1
          fi