name: Validate Schema Change
on:
  issues:
    types: [opened, edited]

jobs:
  validate-schema:
    if: contains(github.event.issue.labels.*.name, 'schema-anpassen')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build Project with Maven
        run: mvn -f TopicConfig/pom.xml clean package

      # Testschritt: Kopiere die Testdatei in den Arbeitsbereich als "uploaded_schema.avsc"
      - name: Copy Test Schema File
        run: cp TopicConfig/test_files/test_schema.avsc uploaded_schema.avsc

      - name: Run SchemaReader
        working-directory: TopicConfig
        run: mvn exec:java -Dexec.mainClass="de.nordlb.kafka.specification.schema.validation.SchemaReader" -e

      - name: Run SchemaReader and capture output
        working-directory: TopicConfig
        run: mvn exec:java -Dexec.mainClass="de.nordlb.kafka.specification.schema.validation.SchemaReader" | tee schema_output.log

      - name: Verify Schema Output
        run: |
          if grep -q "Ausgelesenes Schema:" schema_output.log; then
            echo "Schema wurde erfolgreich ausgelesen."
          else
            echo "Fehler: Schema-Ausgabe nicht gefunden!" && exit 1
          fi